language: php
php:
  - '7.4'
branches:
  only:
    master
before_install:
  - travis_retry composer self-update
install:
  - composer install
script:
  - composer tests
  - composer phpmd
  - composer pdepend
  - cat coverage-report.log